// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQEytLBHuXyPE9Ia7ubgYAxwKmHRsoimc',
    appId: '1:443711732513:web:839a47d27eb7222d229c60',
    messagingSenderId: '443711732513',
    projectId: 'ambios-93dc3',
    authDomain: 'ambios-93dc3.firebaseapp.com',
    storageBucket: 'ambios-93dc3.firebasestorage.app',
    measurementId: 'G-ZWRCNS6ZQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpkJaNbG2fLJ5djvlymutsHb2Sn5HR_E0',
    appId: '1:443711732513:android:868c440939a76e36229c60',
    messagingSenderId: '443711732513',
    projectId: 'ambios-93dc3',
    storageBucket: 'ambios-93dc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKOXryNe_cy8Q-AePN0KaiWLmtnQ8udgY',
    appId: '1:443711732513:ios:6abc595b4d2d552e229c60',
    messagingSenderId: '443711732513',
    projectId: 'ambios-93dc3',
    storageBucket: 'ambios-93dc3.firebasestorage.app',
    iosBundleId: 'com.example.ambios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKOXryNe_cy8Q-AePN0KaiWLmtnQ8udgY',
    appId: '1:443711732513:ios:6abc595b4d2d552e229c60',
    messagingSenderId: '443711732513',
    projectId: 'ambios-93dc3',
    storageBucket: 'ambios-93dc3.firebasestorage.app',
    iosBundleId: 'com.example.ambios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQEytLBHuXyPE9Ia7ubgYAxwKmHRsoimc',
    appId: '1:443711732513:web:0ff21927f42649bc229c60',
    messagingSenderId: '443711732513',
    projectId: 'ambios-93dc3',
    authDomain: 'ambios-93dc3.firebaseapp.com',
    storageBucket: 'ambios-93dc3.firebasestorage.app',
    measurementId: 'G-BP6GDQ8CC1',
  );
}
